services:
  redisdb:
    image: redis:7
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    container_name: redisdb
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgresdb:
    image: postgres:latest
    volumes:
      # host‑path : container‑path
      - ./postgres/init/seeds:/docker-entrypoint-initdb.d
    container_name: postgresdb
    environment:
      POSTGRES_USER: auction_user
      POSTGRES_PASSWORD: auction_password
      POSTGRES_DB: auction_db
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer:latest
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - 9191:8080
    networks:
      - app-network

networks:
  app-network:
    driver_opts:
      com.docker.network.driver.mtu: 1460
